spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: false
  application:
    name: URL Shortener
  mail:
    host: localhost
    port: 8025
    username:
    password:
    properties:
      mail.smtp.auth:

app:
  jwt-base64-secret: MzMzYjg3YTRmYmU0YmM4YzJkZWE4NTJlZGEzMDgzZjkzOWNjM2MwMWQ4NzI2MjgwZWU0MzM5ZTY0MGEzMjg1YzIwMjU1MWM5ZTNkMzg5YWNiMjExNGJlMTE4NjZlMWMxODIxNjYwMTBkZTRiZWRlNzU3MDc5ZThhMDcxMjlkMGE
  email-sender-address: no-reply@hrva.cc
  contact-email: info@localhost
  server-url: localhost
  frontend-url: http://localhost:8081
  anonymous-url-creation-enabled: false

server:
  port: 8080