spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/dbchangelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  error:
    include-message: always

app:
  app-name: Open Url Shortener
  google-api:
    client-id: hrva.cc
    client-version: 1.0.0
  short-url-length: 5
  api-key-calls-limit: 256
  jwt-token-validity-seconds: 36000
  api-key-expiration-in-months: 12
  reset-token-expiration-in-hours: 24
  user-api-key-slots: 4
  inactive-visit-increment-per-ip-in-hours: 2
  ip-retention-duration-in-hours: 48
  deactivate-user-account-after-days: 1825
  max-login-attempts: 20
  registration-enabled: true
  anonymous-url-creation-enabled: false